site_name: 'LayerFX : Layer-Based Effects for URP'
nav:
  - Home: index.md
  - Package Contents: contents.md
  - Quick Start: quick-start-guide.md
  - API Reference: api-reference.md
  - Custom Shaders and Materials: custom-shaders-and-materials.md
  - Performance: performance.md
  - FAQ: faq-and-troubleshooting.md
  - Version Support: version-support.md
theme:
  name: material

  palette:

    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Light mode

  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight